# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/Preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(621, 441)
        Preferences.setModal(True)
        self.formLayoutWidget = QtWidgets.QWidget(Preferences)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 581, 289))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.projectDirectoryLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.projectDirectoryLabel.setObjectName("projectDirectoryLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.projectDirectoryLabel)
        self.projectRoot = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.projectRoot.setObjectName("projectRoot")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.projectRoot)
        self.projectDirectoryWidget = QtWidgets.QWidget(self.formLayoutWidget)
        self.projectDirectoryWidget.setObjectName("projectDirectoryWidget")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.projectDirectoryWidget)
        self.projectDirectoryLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.projectDirectoryLabel_2.setObjectName("projectDirectoryLabel_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.projectDirectoryLabel_2)
        self.templatePath = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.templatePath.setObjectName("templatePath")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.templatePath)
        self.projectDirectoryLabel_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.projectDirectoryLabel_3.setObjectName("projectDirectoryLabel_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.projectDirectoryLabel_3)
        self.projectDirectoryLabel_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.projectDirectoryLabel_4.setObjectName("projectDirectoryLabel_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.projectDirectoryLabel_4)
        self.nextQuoteNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nextQuoteNumber.setObjectName("nextQuoteNumber")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nextQuoteNumber)
        self.nextInvoiceNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nextInvoiceNumber.setObjectName("nextInvoiceNumber")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nextInvoiceNumber)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setGeometry(QtCore.QRect(40, 350, 549, 36))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Preferences)
        self.buttonBox.accepted.connect(Preferences.accept) # type: ignore
        self.buttonBox.rejected.connect(Preferences.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.projectDirectoryLabel.setText(_translate("Preferences", "Project Directory"))
        self.projectDirectoryLabel_2.setText(_translate("Preferences", "Template Directory"))
        self.projectDirectoryLabel_3.setText(_translate("Preferences", "nextQuoteNumber"))
        self.projectDirectoryLabel_4.setText(_translate("Preferences", "nextInvoiceNumber"))
